version: '3'

services:
  country-quiz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: country-quiz
    expose:
      - 80
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=country-quiz.florianfort-dev.fr
      # - VIRTUAL_PORT=3000

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
